server:
  port: 9094

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muzixapplication
    username: amiya559
    password: 143@Arpilu
    platform: mysql
    api-key: NTUzNTQ0OTctNDE2OC00OGRhLThjNTEtNzFmN2Y4NWU0ODYw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto=update: update
  application:
    name: RECOMMEND-MUSIC-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9096/eureka/
  instance:
    hostname: localhost